### ISSUE TITLE
Larger sample icon needed for Slack app

### ISSUE THREAD

**Issue by tdmalone** [tdmalone/slackemon#19]
The [sample icon suggested in the README](https://raw.githubusercontent.com/tdmalone/slackemon/master/_images/emoji/pokeball.png) for users creating their Slackemon Slack apps is 128 x 128 and no longer accepted by Slack:

> Icons must be squares between 512px by 512px and 2000px by 2000px, please!

Need to find an additional icon to use as an app icon (we still need the existing one for emoji use, as larger icons aren't accepted for that).

**Comment by Naramsim** [comment]
Hi, you can use this one 1158x1158
![pokeball](https://cloud.githubusercontent.com/assets/8996268/26577121/94deefde-452b-11e7-8f28-9a9d0fe98b45.png)

**Comment by Naramsim** [comment]
With [Deep learning](http://waifu2x.udp.jp/) I obtained a 2316x2312
![pokeball2x](https://cloud.githubusercontent.com/assets/8996268/26577161/c00946be-452b-11e7-899e-f7abda117a00.png)

**Comment by tdmalone** [comment]
Woah that's amazing! Thanks. :)
