### ISSUE TITLE
Cron token

### ISSUE THREAD

**Issue by Naramsim** [tdmalone/slackemon#2]
`define( 'CRON_TOKEN', 'XXXXXXXXXXXXXXXXXXXX' );` 

Could this variable be autogenerated randomly?

**Comment by juz501** [comment]
I'm pretty sure it's only to prevent access to the cron endpoint directly. It can auto generated, but just needs to be used when you setup the cron script itself.

**Comment by tdmalone** [comment]
Yeah what @juz501 says is correct. You set it and then you use it. That's for 'traditional hosting' though. Cron is going to have to be handled differently if deployed on eg. Heroku... I need to do a bit more reading up on that.

**Comment by Naramsim** [comment]
Ok, thanks for the clarification
