### ISSUE TITLE
Pokeapi is shutting down - Slackémon needs an alternative

### ISSUE THREAD

**Issue by tdmalone** [tdmalone/slackemon#31]
Re: https://github.com/PokeAPI/pokeapi/issues/294

I knew this was [coming at some stage](http://phalt.co/pokeapi-and-swapi-going-forward/) but didn't realise it would be so soon.

Slackémon cannot run without Pokeapi.

I have [forked it](https://github.com/tdmalone/pokeapi) just in case (although Paul isn't going to remove it), but we'll need to look into setting up an instance of it before 1st July. Probably on Heroku? However, Pokeapi gets a lot of use and I won't be able to support everyone who wants to use it, so the instance will probably only be set up for use by Slackémon.

**Comment by Naramsim** [comment]
With docker-compose we can add a local machine that server it APIs. It already has a [compose file](https://github.com/PokeAPI/pokeapi/blob/master/docker-compose.yml). But it will take month to build, on a cheap PC 😄 

Otherwise, you could use [Ninjask](https://github.com/Naramsim/ninjask) which is essentially a repo where all jsons are stored, accessible trough a CDN.
Or [Ditto](https://github.com/pokesource/ditto) as a docker image.

**Comment by tdmalone** [comment]
Ohh I like the Ninjask idea! So essentially the endpoints are all exactly the same, just under the rawgit URL and with index.json at the end?

That shouldn't be hard to implement. Might just write a function to convert the existing API URLs.

Meanwhile I'm also seeing if I can get an instance up on Heroku (getting some Python errors I need to look into), and I'll also try building locally to see how that goes (the ditto repository you linked to has good instructions).

There's also a small discussion on the PokeAPI Slack about others taking over the existing site/API and I've tweeted Paul to see whether he could jump in.

So, there's 3-4 potential solutions. Yay!

**Comment by tdmalone** [comment]
Potential solutions for the collectstatic Python errors on Heroku: https://stackoverflow.com/questions/36665889/collectstatic-error-while-deploying-django-app-to-heroku

**Comment by tdmalone** [comment]
Pokeapi is likely to stay up and running now with someone willing to take it over (as per discussion in Pokeapi Slack).

If it still does go down, I'll switch to using Ninjask instead (although, I do note Ninjask doesn't have files for names, just ids, so might need to update some of our code).

So, I don't think we need to run our own instance for now. But it's always an option in future if required.
