### ISSUE TITLE
Decide on a git branch strategy

### ISSUE THREAD

**Issue by tdmalone** [tdmalone/slackemon#32]
Soon after I put this project on Github, and after @Naramsim's first pull requests, I slightly changed how I was branching. I noticed that @Naramsim then started setting his pull requests to go into my new `tim` branch - which is essentially my 'develop' branch.

To make things clearer, I'm thinking of adopting [A successful Git branching model](http://nvie.com/posts/a-successful-git-branching-model/), minus the release branch flow for now (probably because we're in alpha, we generally just make releases when there's a feature or two that's ready, so that could happen straight from the develop branch). Version bumps would then happen directly after a merge from `develop` into `master`.

This would mean that each 'feature' I work on will have its own branch, which is not too different from how I have been developing [`tests`](https://github.com/tdmalone/slackemon/tree/tests) and [`data-store`](https://github.com/tdmalone/slackemon/tree/data-store). However, rather than merging into [`tim`](https://github.com/tdmalone/slackemon/tree/tim), I would instead merge into `develop`, which is also where @Naramsim and others could make their pull requests into.

Sound alright? @Naramsim?

**Comment by Naramsim** [comment]
Sounds good, thanks.

**Comment by tdmalone** [comment]
Ok this is now done! There is no more `tim` branch.

https://github.com/tdmalone/slackemon/branches
